# -*- coding: utf-8 -*-

import ez_setup
ez_setup.use_setuptools()

from setuptools import setup, Extension

setup(
    name='languageIdentifier',
    version='1.0.1.6',
    license='MIT',
    author='Jeff Graves',
    author_email='decultured@gmail.com',
    description='Language Identification using unicode testing and trigram identification',
    zip_safe=False, # I'm not sure if it is egg safe so I'm erring on the side of caution.
    long_description=__doc__,
	data_files = [
		('languageIdentifier/trigrams', ['trigrams/af.tri']),
		('languageIdentifier/trigrams', ['trigrams/ar.tri']),
		('languageIdentifier/trigrams', ['trigrams/az.tri']),
		('languageIdentifier/trigrams', ['trigrams/bg.tri']),
		('languageIdentifier/trigrams', ['trigrams/ca.tri']),
		('languageIdentifier/trigrams', ['trigrams/ceb.tri']),
		('languageIdentifier/trigrams', ['trigrams/cs.tri']),
		('languageIdentifier/trigrams', ['trigrams/cy.tri']),
		('languageIdentifier/trigrams', ['trigrams/da.tri']),
		('languageIdentifier/trigrams', ['trigrams/de.tri']),
		('languageIdentifier/trigrams', ['trigrams/en.tri']),
		('languageIdentifier/trigrams', ['trigrams/es.tri']),
		('languageIdentifier/trigrams', ['trigrams/et.tri']),
		('languageIdentifier/trigrams', ['trigrams/eu.tri']),
		('languageIdentifier/trigrams', ['trigrams/fa.tri']),
		('languageIdentifier/trigrams', ['trigrams/fi.tri']),
		('languageIdentifier/trigrams', ['trigrams/fr.tri']),
		('languageIdentifier/trigrams', ['trigrams/ha.tri']),
		('languageIdentifier/trigrams', ['trigrams/haw.tri']),
		('languageIdentifier/trigrams', ['trigrams/hi.tri']),
		('languageIdentifier/trigrams', ['trigrams/hr.tri']),
		('languageIdentifier/trigrams', ['trigrams/hu.tri']),
		('languageIdentifier/trigrams', ['trigrams/id.tri']),
		('languageIdentifier/trigrams', ['trigrams/is.tri']),
		('languageIdentifier/trigrams', ['trigrams/it.tri']),
		('languageIdentifier/trigrams', ['trigrams/kk.tri']),
		('languageIdentifier/trigrams', ['trigrams/ky.tri']),
		('languageIdentifier/trigrams', ['trigrams/la.tri']),
		('languageIdentifier/trigrams', ['trigrams/lt.tri']),
		('languageIdentifier/trigrams', ['trigrams/lv.tri']),
		('languageIdentifier/trigrams', ['trigrams/mk.tri']),
		('languageIdentifier/trigrams', ['trigrams/mn.tri']),
		('languageIdentifier/trigrams', ['trigrams/ne.tri']),
		('languageIdentifier/trigrams', ['trigrams/nl.tri']),
		('languageIdentifier/trigrams', ['trigrams/nso.tri']),
		('languageIdentifier/trigrams', ['trigrams/pl.tri']),
		('languageIdentifier/trigrams', ['trigrams/ps.tri']),
		('languageIdentifier/trigrams', ['trigrams/pt.tri']),
		('languageIdentifier/trigrams', ['trigrams/ro.tri']),
		('languageIdentifier/trigrams', ['trigrams/ru.tri']),
		('languageIdentifier/trigrams', ['trigrams/sk.tri']),
		('languageIdentifier/trigrams', ['trigrams/sl.tri']),
		('languageIdentifier/trigrams', ['trigrams/so.tri']),
		('languageIdentifier/trigrams', ['trigrams/sq.tri']),
		('languageIdentifier/trigrams', ['trigrams/sr.tri']),
		('languageIdentifier/trigrams', ['trigrams/sv.tri']),
		('languageIdentifier/trigrams', ['trigrams/sw.tri']),
		('languageIdentifier/trigrams', ['trigrams/tl.tri']),
		('languageIdentifier/trigrams', ['trigrams/tlh.tri']),
		('languageIdentifier/trigrams', ['trigrams/tn.tri']),
		('languageIdentifier/trigrams', ['trigrams/tr.tri']),
		('languageIdentifier/trigrams', ['trigrams/ts.tri']),
		('languageIdentifier/trigrams', ['trigrams/uk.tri']),
		('languageIdentifier/trigrams', ['trigrams/ur.tri']),
		('languageIdentifier/trigrams', ['trigrams/uz.tri']),
		('languageIdentifier/trigrams', ['trigrams/ve.tri']),
		('languageIdentifier/trigrams', ['trigrams/xh.tri']),
		('languageIdentifier/trigrams', ['trigrams/zu.tri']),
	],
	ext_modules = [
		Extension('languageIdentifier', 
		[	"identifier/language_detector.cpp", 
			"identifier/language_database.cpp", 
			"identifier/language_sample.cpp", 
			"identifier/trigram.cpp", 
			"identifier/unicode_tester.cpp", 
			"identifier/murmur/murmur.cpp", 
			"identifier/unicode/utf8.c", 
		],
		depends=[
			"identifier/language_database.h", 
			"identifier/language_sample.h", 
			"identifier/trigram.h", 
			"identifier/unicode_tester.h", 
			"identifier/murmur/murmur.h", 
			"identifier/unicode/utf8.h", 
		],
		include_dirs=['identifier','identifier/murmur', 'identifier/unicode'],
		libraries=['z'],
		language='c++')
	],
    platforms='any',
    classifiers=[
        'Development Status :: Beta',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: C++',
        'Topic :: Software Development',
        'Topic :: Software Development :: Libraries :: Python Modules'
    ],
	packages=[]
)
